import { Injectable } from '@angular/core';
import { Intern } from './intern.model';

@Injectable({
  providedIn: 'root'
})
export class InternDataService {
  interns: Intern[] = [
    { sNo: 1, internId: 'I346', name: 'Deepan Chakkaravarthi', location: 'Chennai', programmingLanguage: 'Python', officialCompanyEmailId: 'deepan.chakkaravarthi@ilink-systems.com', collegeName: 'REC', primarySkill: 'Python,SQL', secondarySkill: 'Cloud computing,RPA', areaOfInterest: 'Cloud Computing', allocatedBU: 'DATA' },
    { sNo: 2, internId: 'I347', name: 'Logesh Kanna', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'logesh.kanna@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java,SQL', secondarySkill: 'HTML,CSS,Python', areaOfInterest: 'Web development , Data Analytics', allocatedBU: 'DATA' },
    { sNo: 3, internId: 'I348', name: 'Aravind S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'aravind.s@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java,SQL,RPA', secondarySkill: 'UI/UX', areaOfInterest: 'Automation, Data Analytics', allocatedBU: 'DEX' },
    { sNo: 4, internId: 'I349', name: 'Gayathri Priya', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'gayathri.priya@ilink-systems.com', collegeName: 'REC', primarySkill: 'Cybersecurity(pentesting),RPA,JAVA,SQL', secondarySkill: 'Cloud computing,UI/UX', areaOfInterest: 'Cybersecurity,Data Analytics', allocatedBU: 'DATA' },
    { sNo: 5, internId: 'I350', name: 'Mohamed Aadhil', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'mohamed.aadhil@ilink-systems.com', collegeName: 'REC', primarySkill: 'Backend Development(Node JS),Gen AI, Devops', secondarySkill: 'Data and Cloud Engineering', areaOfInterest: 'Data Engineering,Gen AI,Cloud and Security', allocatedBU: 'DEX' },
    { sNo: 6, internId: 'I351', name: 'Raveena Sri', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'raveena.sri@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java, SQL,Cloud computing,Data Structures', secondarySkill: 'Data Analytics, AI/ML,SDLC', areaOfInterest: 'Data Analytics, Web Development', allocatedBU: 'DATA' },
    { sNo: 7, internId: 'I352', name: 'Sri Sai', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'sri.sai@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java, SQL', secondarySkill: 'RPA , UI/UX', areaOfInterest: 'Data analytics,Data Science ,Automation', allocatedBU: 'DATA' },
    { sNo: 8, internId: 'I353', name: 'Keerthi S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'keerthi.s@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java,SQL', secondarySkill: 'HTML,CSS', areaOfInterest: 'Full Stack development', allocatedBU: 'DATA' },
    { sNo: 9, internId: 'I354', name: 'Madhubala Rajendiran', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'madhubala.rajendiran@ilink-systems.com', collegeName: 'REC', primarySkill: 'java ,SQL', secondarySkill: 'Python', areaOfInterest: 'Data Analytics, Data Science', allocatedBU: 'DEX' },
    { sNo: 10, internId: 'I356', name: 'Kalaivendhan S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'kalaivendhan.s@ilink-systems.com', collegeName: 'REC', primarySkill: 'java,Machine Learning', secondarySkill: 'Data Analytics,SQL', areaOfInterest: 'Data Science', allocatedBU: 'DATA' },
    { sNo: 11, internId: 'I357', name: 'Prabakar Kesavan', location: 'Chennai', programmingLanguage: 'Python', officialCompanyEmailId: 'prabakar.kesavan@ilink-systems.com', collegeName: 'REC', primarySkill: 'Python , SQL', secondarySkill: 'RPA', areaOfInterest: 'Data Analytics, Data Science', allocatedBU: 'DATA' },
    { sNo: 12, internId: 'I358', name: 'Karthikeyan Vasudevan', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'karthikeyan.vasudevan@ilink-systems.com', collegeName: 'REC', primarySkill: 'Java, Problem solving', secondarySkill: '3D Modelling (Maya) , python, Basic RPA', areaOfInterest: 'Backend Development', allocatedBU: 'DATA' },
    { sNo: 13, internId: 'I359', name: 'Ansari Zayd', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'ansari.zayd@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Data Science, Machine Learning', secondarySkill: 'Gen-AI, Analytics', areaOfInterest: 'AI/ML, Data Science', allocatedBU: 'DATA' },
    { sNo: 14, internId: 'I360', name: 'Shravani Karbhajane', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'shravani.karbhajane@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Data Science', secondarySkill: 'image processing , Web development', areaOfInterest: 'Data Science, Machine Learning', allocatedBU: 'IAT' },
    { sNo: 15, internId: 'I361', name: 'Swaroop Khadke', location: 'Pune', programmingLanguage: 'C++', officialCompanyEmailId: 'swaroop.khadke@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Data Analysis , Web Development', secondarySkill: 'Cloud,DBMS', areaOfInterest: 'Cloud', allocatedBU: 'DATA' },
    { sNo: 16, internId: 'I362', name: 'Lalit Chaudhari', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'lalit.chaudhari@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Data Science, Machine Learning, Java', secondarySkill: 'Gen-AI, Web development', areaOfInterest: 'AI/ML/web Development', allocatedBU: 'DATA' },
    { sNo: 17, internId: 'I363', name: 'Sanket Dhakane', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'sanket.dhakane@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Web Development, Java,SQL,DSA', secondarySkill: 'Cloud computing,MongoDb', areaOfInterest: 'AI/Ml,Data Analytics, Data Engineering', allocatedBU: 'DATA' },
    { sNo: 18, internId: 'I364', name: 'Gaurav Khole', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'gaurav.khole@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'React.js, Google Firebase, Node.js', secondarySkill: 'Knowledge about Computer hardware and Troubleshooting the same', areaOfInterest: '', allocatedBU: 'DEX' },
    { sNo: 19, internId: 'I365', name: 'Rajat Mahajan', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'rajat.mahajan@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Web Dev, Java, SQL', secondarySkill: 'Cloud Computing, DBMS, AI', areaOfInterest: 'Web Dev, AI', allocatedBU: 'DEX' },
    { sNo: 20, internId: 'I366', name: 'Prafulla Badgujar', location: 'Pune', programmingLanguage: 'C++', officialCompanyEmailId: 'prafulla.badgujar@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Web Development,Machine Learning', secondarySkill: 'Cloud Computing, DBMS', areaOfInterest: 'Data Science,GenAI,Data Analytics', allocatedBU: 'DEX' },
    { sNo: 21, internId: 'I367', name: 'Ankush Kaudi', location: 'Pune', programmingLanguage: 'C++', officialCompanyEmailId: 'ankush.kaudi@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Ethical Hacking, Web development', secondarySkill: 'Cloud technology', areaOfInterest: 'Cybersecurity and Web Development', allocatedBU: 'DEX' },
    { sNo: 22, internId: 'I368', name: 'Vedant Kavhar', location: 'Pune', programmingLanguage: 'C++', officialCompanyEmailId: 'vedant.kavhar@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Full Stack Developement', secondarySkill: 'Cloud computing', areaOfInterest: 'Web developement,ai,ml,ds,blockchain', allocatedBU: 'DEX' },
    { sNo: 23, internId: 'I369', name: 'Chinmay Saraf', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'chinmay.saraf@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Ml, Data Science,Generative AI,Python', secondarySkill: '', areaOfInterest: '', allocatedBU: 'DEX' },
    { sNo: 24, internId: 'I370', name: 'Apurva Belsare', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'apurva.belsare@ilink-systems.com', collegeName: 'VIIT Pune', primarySkill: 'Machine Learning, SQL', secondarySkill: 'Data Analytics', areaOfInterest: 'Data Science, Machine Learning', allocatedBU: 'IAT' },
    { sNo: 25, internId: 'I371', name: 'Aditya Gode', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'aditya.gode@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Java, Machine Learning', secondarySkill: 'Data Science, SQL', areaOfInterest: 'Cybersecurity and Cloud Engineering', allocatedBU: 'DEX' },
    { sNo: 26, internId: 'I372', name: 'Prutha Annadate', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'prutha.annadate@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science', secondarySkill: 'Business Analytics', areaOfInterest: 'Data Science', allocatedBU: 'DATA' },
    { sNo: 27, internId: 'I373', name: 'Nishant Kshirsagar', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'nishant.kshirsagar@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Machine Learning', secondarySkill: 'Natural Language Processing', areaOfInterest: 'Conversational AI', allocatedBU: 'DATA' },
    { sNo: 28, internId: 'I374', name: 'Kushal Shah', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'kushal.shah@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science,Gen AI', secondarySkill: 'M.L,Analytics,Web Dev', areaOfInterest: 'A.I/Gen A.I', allocatedBU: 'DATA' },
    { sNo: 29, internId: 'I375', name: 'Unmesh Mathakari', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'unmesh.mathakari@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science , Web Dev', secondarySkill: 'NLP, ML', areaOfInterest: 'Data science, Blockchain', allocatedBU: 'DATA' },
    { sNo: 30, internId: 'I376', name: 'Saanvi Kulkarni', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'saanvi.kulkarni@ilink-systmes.com', collegeName: 'MIT WPU', primarySkill: 'Data Science, ML', secondarySkill: 'Analytics', areaOfInterest: 'Data Science', allocatedBU: 'DATA' },
    { sNo: 31, internId: 'I377', name: 'Janhavi Kherdekar', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'janhavi.kherdekar@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science', secondarySkill: 'Machine Learning, NLP,GenAI', areaOfInterest: 'Data Science, Machine Learning', allocatedBU: 'DATA' },
    { sNo: 32, internId: 'I378', name: 'Reet Shinde', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'reet.shinde@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Machine Learning', secondarySkill: 'AI', areaOfInterest: 'Natural Language Processing', allocatedBU: 'DATA' },
    { sNo: 33, internId: 'I379', name: 'Yuvraj Lamba', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'yuvraj.lamba@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science,Gen AI', secondarySkill: 'Business Analytics', areaOfInterest: 'Artificial Intelligence, GenAI', allocatedBU: 'DATA' },
    { sNo: 34, internId: 'I380', name: 'Rahul Metre', location: 'Pune', programmingLanguage: 'Java', officialCompanyEmailId: 'rahul.metre@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Backend Development, SQL, Java', secondarySkill: 'AI/ML, NLP,Data Science', areaOfInterest: 'Web Dev', allocatedBU: 'DEX' },
    { sNo: 35, internId: 'I381', name: 'Anshul Chandra', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'anshul.chandra@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Data Science, ML', secondarySkill: 'NLP', areaOfInterest: 'AI, Data Science', allocatedBU: 'DATA' },
    { sNo: 36, internId: 'I382', name: 'Lavanya Singh', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'lavanya.singh@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Machine Learning, Data Science', secondarySkill: 'Analytics', areaOfInterest: 'Data Science/ GenAI', allocatedBU: 'DATA' },
    { sNo: 37, internId: 'I383', name: 'Parth Dhabalia', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'parth.dhabalia@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Machine Learning, AI, Data Science', secondarySkill: 'Image processing ,Power BI', areaOfInterest: '', allocatedBU: 'DATA' },
    { sNo: 38, internId: 'I384', name: 'Bhagyesh Dhoble', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'bhagyesh.dhoble@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Generative AI', secondarySkill: 'Multi Agentic Workflow', areaOfInterest: 'AI/ML/Data Science', allocatedBU: 'DATA' },
    { sNo: 39, internId: 'I385', name: 'Chris Levi', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'chris.levi@ilink-systems.com', collegeName: 'MIT WPU', primarySkill: 'Machine Learning', secondarySkill: 'Analytics', areaOfInterest: 'AL/ML,Data Science', allocatedBU: 'DEX' },
    { sNo: 40, internId: 'I386', name: 'Visnupriyaa Bothurajan', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'visnupriyaa.b@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java,C,Basics of Power BI,HTML,CSS', secondarySkill: 'Python', areaOfInterest: '', allocatedBU: 'DEX' },
    { sNo: 41, internId: 'I387', name: 'Sree Suvetha Ganesan', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'sreesuvetha.ganesan@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java, SQL, HTML, CSS, C', secondarySkill: 'Power BI, Python', areaOfInterest: 'Web development, Data analytics', allocatedBU: 'DEX' },
    { sNo: 42, internId: 'I388', name: 'Thanzia Z', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'thanzia.z@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java, SQL, Django web developement, HTML, CSS , Python', secondarySkill: 'Power BI , ML , C', areaOfInterest: 'Web development , Data Science , Data Analytics', allocatedBU: 'DEX' },
    { sNo: 43, internId: 'I389', name: 'Barath S', location: 'Trichy', programmingLanguage: 'Python', officialCompanyEmailId: 'barath.s@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Python, SQL, Data Structures', secondarySkill: 'C/C++', areaOfInterest: 'Data Analytics, Data Science', allocatedBU: 'DATA' },
    { sNo: 44, internId: 'I390', name: 'Jocelyn Raj', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'jocelyn.raj@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java,SQL', secondarySkill: 'Data Analytics', areaOfInterest: 'Data Analytics, Data Engineering', allocatedBU: 'DATA' },
    { sNo: 45, internId: 'I391', name: 'Harikaran M', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'harikaran.m@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Python, SQL, Power BI, C, Java, Data Visualization, Statistical Analysis, DSA', secondarySkill: 'Big data(GCP), Keras, Machine Learning, Data Wrangling, HTML, CSS, JavaScript', areaOfInterest: 'Data Engineering, Business Intelligence', allocatedBU: 'DATA' },
    { sNo: 46, internId: 'I392', name: 'Balaji SD', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'balaji.sd@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java, SQL', secondarySkill: 'C, Python', areaOfInterest: 'App Development', allocatedBU: 'DATA' },
    { sNo: 47, internId: 'I393', name: 'Gokula Krishnan', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'gokula.krishnan@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java ,SQL', secondarySkill: 'Backend Development,Data Analytics', areaOfInterest: 'Web development', allocatedBU: 'DATA' },
    { sNo: 48, internId: 'I394', name: 'Dhanusri S K', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'dhanushri.sk@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Web development,Java,Python,UI&UX', secondarySkill: 'SQL,PHP,React.js,C,Node.js,MongoDB,Meta Spark', areaOfInterest: 'Full Stack,DBMS, Cloud ,Data analytics,AI,UI&UX', allocatedBU: 'DATA' },
    { sNo: 49, internId: 'I395', name: 'Tamilarasan S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'tamilarasan.s@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Java,SQL', secondarySkill: 'HTML, CSS,UI/UX', areaOfInterest: 'Web development', allocatedBU: 'DEX' },
    { sNo: 50, internId: 'I396', name: 'Srinithi V', location: 'Chennai', programmingLanguage: 'Python', officialCompanyEmailId: 'srinithi.v@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Python, Java, HTML, CSS, JavaScript', secondarySkill: 'SQL ,React, C/C++', areaOfInterest: 'Web development, Data analytics', allocatedBU: 'DEX' },
    { sNo: 51, internId: 'I397', name: 'Prem Kumar S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'premkumar.s@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Java ,SQL', secondarySkill: 'HTML,CSS,UI/UX', areaOfInterest: 'Web Development', allocatedBU: 'DEX' },
    { sNo: 52, internId: 'I398', name: 'Gokul K', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'gokul.k@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Java, Front End Developer (HTML,CSS ,ReactJS)', secondarySkill: 'MySql , UI/UX(Figma)', areaOfInterest: 'Web Development,UI developement', allocatedBU: 'DATA' },
    { sNo: 53, internId: 'I399', name: 'Devadarshini K A', location: 'Trichy', programmingLanguage: 'Python', officialCompanyEmailId: 'devadarshini.ka@ilink-systems.com', collegeName: 'AUBIT Trichy', primarySkill: 'Web Development , Python, java ,C,UIUX, Software Engineering', secondarySkill: 'Meta Spark. Network Essentials,App Development, Animation,react , node js, mongo db,SQL, Power BI Excel', areaOfInterest: 'Data Analytics, Data Science,Gen AI , Forecasting', allocatedBU: 'DATA' },
    { sNo: 54, internId: 'I400', name: 'Abdullah Firdowsi', location: 'Chennai', programmingLanguage: 'Python', officialCompanyEmailId: 'abdullah.firdowsi@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Python, SQL', secondarySkill: 'DevOps, Cloud Computing', areaOfInterest: 'Data Science, Business Analytics', allocatedBU: 'DEX' },
    { sNo: 55, internId: 'I401', name: 'Sharuthi S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'sharuthi.s@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java,SQL', secondarySkill: 'HTML, CSS,UI/UX', areaOfInterest: 'Web development', allocatedBU: 'DATA' },
    { sNo: 56, internId: 'I402', name: 'Azeeza Banu  S J', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: ' azeezabanu.sj@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java,Sql', secondarySkill: 'HTML,CSS,UI/UX', areaOfInterest: 'Web development', allocatedBU: 'DATA' },
    { sNo: 57, internId: 'I403', name: 'Logesh M', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'logesh.m@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java, HTML, CSS, SQL, JavaScript', secondarySkill: 'C, Python, React', areaOfInterest: 'Web development, Data analytics', allocatedBU: 'DEX' },
    { sNo: 58, internId: 'I404', name: 'Guna Kuppuchamy', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'guna.kuppuchamy@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java, MERN stack', secondarySkill: 'HTML, CSS, javascript, sql', areaOfInterest: 'Full Stack development', allocatedBU: 'DEX' },
    { sNo: 59, internId: 'I405', name: 'Swetha Shri S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'swetha11cbe@gmail.com', collegeName: 'Karpagam', primarySkill: 'Cloud Computing', secondarySkill: 'UI/UX', areaOfInterest: 'Cloud Computing', allocatedBU: 'DATA' },
    { sNo: 60, internId: 'I406', name: 'Gugan MK', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'gugan.mk@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java , MERN', secondarySkill: 'UI/UX', areaOfInterest: 'Web development , Data Analytics', allocatedBU: 'DEX' },
    { sNo: 61, internId: 'I407', name: 'Palaniappan N', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'palaniappan.n@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java, SQL', secondarySkill: 'HTML, CSS', areaOfInterest: 'Web development, Data analytics', allocatedBU: 'DATA' },
    { sNo: 62, internId: 'I408', name: 'Dhinesh L', location: 'Chennai', programmingLanguage: 'Python', officialCompanyEmailId: 'dhinesh.l@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Python,Machine Learning,Power BI', secondarySkill: 'Data Science', areaOfInterest: 'Gen AI,Data visualization', allocatedBU: 'DATA' },
    { sNo: 63, internId: 'I409', name: 'Anuranjani Vasudevan', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'anuranjani.vasudevan@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java,SQL', secondarySkill: 'HTML5,CSS,Bootstrap,Javascript,React.js,Node.js,MongoDB,Python', areaOfInterest: 'Web development,Data Analytics,Data Science', allocatedBU: 'DATA' },
    { sNo: 64, internId: 'I410', name: 'Saktheeswari D', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'saktheeswari.d@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'SQL,Java', secondarySkill: 'C, Python,JS', areaOfInterest: 'Data Analytics, AI/ML', allocatedBU: 'DATA' },
    { sNo: 65, internId: 'I411', name: 'Mohana Gowri', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'mohana.gowri@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java,SQL', secondarySkill: 'UI/UX,HTML,CSS', areaOfInterest: 'Web development', allocatedBU: 'DEX' },
    { sNo: 66, internId: 'I412', name: 'Mathesh M', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'mathesh.m@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Java, SQL, Data Structures', secondarySkill: 'C, HTML, CSS, JS', areaOfInterest: 'Software Development, Data Analytics', allocatedBU: 'DATA' },
    { sNo: 67, internId: 'I413', name: 'Dilip S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'dilip.s@ilink-systems.com', collegeName: 'Karpagam', primarySkill: 'Web Development, Java', secondarySkill: 'MySQL', areaOfInterest: 'Data Analytics, Data Science, AI/ML', allocatedBU: 'DEX' },
    { sNo: 68, internId: 'I414', name: 'Akash  Sheri', location: 'Pune', programmingLanguage: 'Python', officialCompanyEmailId: 'akash.sheri@ilink-systems.com', collegeName: 'Jain', primarySkill: 'React Js,MREN stack , web Development', secondarySkill: 'python, C program, Data Analytics', areaOfInterest: 'Data analytics , Power Bi, web development', allocatedBU: 'DATA' },
    { sNo: 69, internId: 'I418', name: 'Abirami V', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'abirami.v@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java,SQL', secondarySkill: 'Backend Development,DSA', areaOfInterest: 'Web development', allocatedBU: 'DATA' },
    { sNo: 70, internId: 'I419', name: 'Chaarubhala S', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'chaarubhala.s@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Power BI,Data Analytics', secondarySkill: 'AI,Machine Learning', areaOfInterest: 'Data analytics , Power Bi, web development', allocatedBU: 'DATA' },
    { sNo: 71, internId: 'I420', name: 'Kishore Kumar S', location: 'Trichy', programmingLanguage: 'Java', officialCompanyEmailId: 'kishore.kumar@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java,SQL,DSA', secondarySkill: 'Cloud Computing,Python', areaOfInterest: 'Data analytics,Data Science ,CyberSecurity', allocatedBU: 'DATA' },
    { sNo: 72, internId: 'I421', name: 'Ishwarya S', location: 'Chennai', programmingLanguage: 'Java', officialCompanyEmailId: 'ishwarya.s@ilink-systems.com', collegeName: 'Saranathan', primarySkill: 'Java, SQL, UI/UX', secondarySkill: 'Data Analytics, Python', areaOfInterest: 'Data science, Data Analytics, Cloud computing', allocatedBU: 'DATA' },
    // Add more sample data here
  ];

  constructor() { }

  getInterns() {
    return this.interns;
  }
}